graph [
	node [ id 0 label "C" ]
	node [ id 1 label "C" ]
	node [ id 2 label "C" ]
	node [ id 3 label "C" ]
	node [ id 4 label "C" ]
	node [ id 5 label "O" ]
	node [ id 6 label "O" ]
	node [ id 7 label "O" ]
	node [ id 8 label "O" ]
	node [ id 9 label "O" ]
	node [ id 10 label "P" ]
	node [ id 11 label "O" ]
	node [ id 12 label "O" ]
	node [ id 13 label "O" ]
	node [ id 14 label "H" ]
	node [ id 15 label "H" ]
	node [ id 16 label "H" ]
	node [ id 17 label "H" ]
	node [ id 18 label "H" ]
	node [ id 19 label "H" ]
	node [ id 20 label "H" ]
	node [ id 21 label "H" ]
	node [ id 22 label "H" ]
	node [ id 23 label "H" ]
	node [ id 24 label "H" ]
	edge [ source 4 target 3 label "-" ]
	edge [ source 5 target 4 label "=" ]
	edge [ source 3 target 2 label "-" ]
	edge [ source 6 target 3 label "-" ]
	edge [ source 2 target 1 label "-" ]
	edge [ source 7 target 2 label "-" ]
	edge [ source 1 target 0 label "-" ]
	edge [ source 8 target 1 label "-" ]
	edge [ source 9 target 0 label "-" ]
	edge [ source 11 target 10 label "=" ]
	edge [ source 12 target 10 label "-" ]
	edge [ source 10 target 9 label "-" ]
	edge [ source 13 target 10 label "-" ]
	edge [ source 14 target 0 label "-" ]
	edge [ source 15 target 0 label "-" ]
	edge [ source 16 target 1 label "-" ]
	edge [ source 17 target 2 label "-" ]
	edge [ source 18 target 3 label "-" ]
	edge [ source 19 target 4 label "-" ]
	edge [ source 20 target 6 label "-" ]
	edge [ source 21 target 7 label "-" ]
	edge [ source 22 target 8 label "-" ]
	edge [ source 23 target 12 label "-" ]
	edge [ source 24 target 13 label "-" ]
]
